version: '3'
services:
  cram-vrb-lab:
    image: cram-vrb-lab:main
    build:
      context: ../
      dockerfile: ./binder/Dockerfile
    user: root
    working_dir: /home/jovyan/work
    command: jupyter lab --allow-root --NotebookApp.token='' --no-browser --ip=0.0.0.0
    ports:
      - 8888:8888
    volumes:
      - ../:/home/jovyan/work:rw
      - /usr/share/vulkan/icd.d/:/etc/vulkan/icd.d
      - ${PWD}/isaacsim-cache/cache/kit:/isaac-sim/kit/cache
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ACCEPT_EULA="YES"
      - PRIVACY_CONSENT="YES"
      - OMNI_KIT_ACCEPT_EULA="YES"
      - OMNI_KIT_ALLOW_ROOT=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
